version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      next-react:
        patterns: ["next", "react", "react-dom", "@types/react", "@types/react-dom", "eslint-config-next"]
      everything-else:
        patterns: ["*"]
        exclude-patterns: ["next", "react", "react-dom", "@types/react", "@types/react-dom", "eslint-config-next"]
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
