interface Image {
    src: string;
    alt: string;
    }



export const images: Image[] = [
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
    {
        src:"/gallery/kuv1.jpg",
        alt:"kuv1"
    },
]
