export interface Pesmi {
    title: string;
    text: string[];
    source: string;
    mp3Url?: string;
    mp3Sub?: string;
}

export const pesmi: Pesmi[] = [
    {
        title: "Ulična trojka",
        text: [
            "V mestu skrito dvorišče med hišami,",
            "davno zakopani spominki,",
            "podobe živalic s čokolade.",
            "Peskovnik se s peskom igra,",
            "le mene ni več in Sandre in Vladeka,",
            "ulične trojke.",
            "",
            "Tam",
            "so posekali mojo najljubšo brezo,",
            "pomendrali cvetlični vrt sosede Elzi,",
            "grm kopriv iztrebili,",
            "češnjo razrezali,",
            "kislic za žvečenje tudi ni več.",
            "",
            "Ni več trave,",
            "le asfalt in pločevina,",
            "parking, plot,",
            "okrušena fasada.",
            "V besedah in pogledih",
            "napetost, ki raste.",
            "",
            "Kje so",
            "vse lesene klopi,",
            "kje Črni Peter, šnops in lažnivec?",
            "Kje vešala za perilo,",
            "ki so delovala na dvojino?",
            "",
            "Zdaj vlada drugi čas.",
            "Vrata hodnikov se zaklepajo,",
            "kolesa zapirajo v kleti",
            "in nikogar pod oknom ni,",
            "da bi klical tvoje ime.",
            "",
            "V mestu",
            "skrito dvorišče med hišami.",
            "Še vedno so zakopani spominki",
            "in pesek se s peskom igra",
            "in jaz in Sandra in Vladek",
            "sedimo vsak na svojem stopnišču",
            "svojega dvorišča."
        ],
        source: "Ostanek umrle zvezde"
    },
    {
        title: "Pismo",
        text: [
            "Ah, saj ne vem več,",
            "zakaj sem se tako odločila,",
            "a poslala ti bom pismo.",
            "",
            "Zeleno ovojnico,",
            "naslov",
            "z umetelnimi črkami.",
            "",
            "Potrebujem svetlobo,",
            "hipna je,",
            "senca se širi.",
            "",
            "Ne vem več zakaj,",
            "a napisala ti bom pismo.",
            "Vsak dan.",
            "",
            "Pozabljena navada je to,",
            "misli zlagati na papir.",
            "",
            "Tudi jokati je pozabljena navada.",
            "Danes jočem samo še znotraj.",
            "Nočem vsak dan jokati,",
            "četudi tema lega v hišo.",
            "",
            "Dragi,",
            "napisala sem ti pismo,",
            "a kako,",
            "da tvoj naslov ni več moj?"
        ],
        source: "Ostanek umrle zvezde"
    },
    {
        title: "sprehod skozi mesto",
        text: [
            "nikoli nisem slutila",
            "da bo sprehod",
            "skozi rodno mesto",
            "boleče in temačno",
            "drsenje po sebi",
            "",
            "v ugodju",
            "svoje nečimrnosti",
            "sem verjela preroku",
            "<em>tujstvo je usoda",
            "tega vročega prašnega mesta </em>",
            "",
            "koliko ljudi",
            "iz tiste moje ulice",
            "danes nosim s seboj",
            "in jih selim v telesa neznancev",
            "",
            "nikoli nisem slutila",
            "kako bom",
            "ob vsaki vrnitvi stopljena",
            "meduza na soncu",
            "lisa na vročem kamnu"
        ],
        source: "Ostanek umrle zvezde"
    },
    {
        title: "ad astra",
        text: [
            "<em> v naslednjem Vesolju </em>",
            "",
            "… morda srečamo svojo podobo",
            "",
            "in spregovorimo o stvareh",
            "ki smo jih zamolčali",
            "",

            "… morda odkrijemo",
            "kdo je bil senca",
            "oko v ključavnici",
            "ko smo polnili zlate skrinje z lažmi",
            "",
            "pozeble ulice se bodo odtalile",
            "in veje bodo slekle ledene liste",
            "pod sojem novega ozvezdja",
            "<em> v naslednjem Vesolju</em>",
            "",
            "lahko pa molčimo",
            "kletko odpremo",
            "in izpustimo",
            "vse besede",
            "iz prsi",
            "nazaj v divjino",
            "",
            "in poletimo v Tišino",
            "v neskončno modrino",
            "se pretopimo",
            "pod sojem novega ozvezdja",
            "<em>v naslednjem Vesolju</em>",
            "",
            "… jata se je vrnila",
            "da ji obrišemo ločila",
            "<em>Zemlja ima eno stranico zaprto</em>",
            "<em>Univerzum leži v travi z rokami pod glavo</em>"
        ],
        source: "Dež v gugalnici",
        mp3Url: "/audio/poezija/ad_astra.mp3",
        mp3Sub : "Pesem je uglasbena, uglasbil in izvaja jo kantavtor Peter Andrej."
    },
    {
        title: "noč nad mestom",
        text: [
            "noč nad mestom",
            "nad strehami",
            "dimniki",
            "zvoniki",
            "",
            "nad krošnjami v parku",
            "zgodbami žabjih mlak",
            "koraki vrtnih poti",
            "",
            "nad zaspanimi",
            "reklamnimi panoji",
            "nemimi ovinki",
            "",
            "nad kokošnjakom",
            "ki čaka",
            "lisjaka",
            "",
            "nad nami",
            "spečimi",
            "v isti srajci sanj",
            "",
            "noč",
            "s pošvedranim krajcem",
            "in cvrčanjem škržatov"
        ],
        source: "Dež v gugalnici",
        mp3Url: "/audio/poezija/noc.mp3",
        mp3Sub : "Pesem je uglasbena, uglasbil in izvaja jo kantavtor Peter Andrej."
    },
    {
        title: "Veronika na kolesu",
        text: [
            "Veronika na kolesu",
            "",
            "z ilovico in deževnico diha Prometej",
            "oživele so skulpture",
            "s krvjo krvodajalcev",
            "ali vejo?",
            "ne razumejo kar gledajo",
            "so bogovi in so boginje",
            "",
            "kdo se tam vozi na zlatem kolesu?",
            "",
            "nejade se igrajo s spečim psom",
            "na otoku blaženih",
            "piranhe spijo",
            "in povodni ježi mahajo z repki",
            "",
            "straža z očmi pod ruto",
            "spremlja mrože z visokimi čeli",
            "razvezane kravate drsijo",
            "po prsih na konice plavuti",
            "",
            "skupinska fotografija spet ne bo prava",
            "trije na njej imajo zaprte misli",
            "otok blaženih čaka",
            "",
            "Veronika že na cesti neba"
        ],
        source: "Dež v gugalnici",
    }
];
