import { Pesmi } from "../poezija/data";

export const pesmi: Pesmi[] = [
    {
        title: "Rastem do tebe",
        text: [
            "<b>Mama</b>,",
            "Moja mama ni takšna",
            "kot je tvoja!",
            "Moja mama ni podobna",
            "nobeni mami!",
            "",
            "Moja mama",
            "je mehka kot pižama,",
            "diši kot",
            "najboljši žvečilni.",
            "",

            "Res je posebna,",
            "zna bit vsevedna,",
            "ne posluša ne Micke ne Pepice,",
            "niti svoje šefice.",
            "",

            "Vedno je špica,",
            "ko v pečici je pica,",
            "v hladilniku čokolada,",
            "mamina razvada.",
            "",
            "Z mano se podi po sobi,",
            "to je njen najljubši hobi,",
            "po postelji skače,",
            "včasih oponaša kače ...",
            "",

            "A moja mama",
            "zna tudi renčati,",
            "kriliti z rokami",
            "in cepetati.",
            "",
            "Takrat je neurje pri nas doma.",
            "Mama je velik in težek oblak,",
            "bliska se, grmi in piha …",
            "Z bratom zakleneva usta vsa tiha,",
            "oče si brke ravna in jih viha …",
            "",
            "Ko nevihta mine",
            "in pride sonce,",
            "je mama zopet moja mami,",
            "toplonežna, podobna pižami,",
            "nasmejana, razigrana."
        ],
        source: "Ostanek umrle zvezde",
        mp3Url: "/audio/za-otroke/mama.mp3",
        mp3Sub: "Pesem je uglasbena, uglasbil in izvaja jo kantavtor Peter Andrej.<br/>Poje Barbara Gabrielle."
    },
    {
        title: "Kdaj je pomlad?",
        text: [
            "Se zgodi takrat,",
            "ko luža v Evo skoči",
            "in jo do kože premoči?",
            "",
            "Ko listje se v drevje oblači",
            "in hiša mamo zrači?",
            "",
            "Je to takrat,",
            "ko veja vrano obsedi,",
            "takrat, ko trava dež ozeleni?",
            "",
            "Kdaj je pomlad?",
            "",
            "Ko čebela sonce prebudi",
            "in med medvedko zasladi?",
            "",
            "Ko se nebo sred utrinka ustavi",
            "in te daljava pozdravi na dlani?",
            "",
            "Ko gnezda nove ptice pletejo",
            "in se vsi od samote gnetejo?",
            "",
            "Kdaj je pomlad?",
            "",
            "Svet stoji na glavi,",
            "vse se za trenutek ustavi,",
            "ko ti imaš rad,",
            "je v tebi zaklad!",
            "",
            "Takrat je pomlad!"
        ],
        source: "Ostanek umrle zvezde",
        mp3Url: "/audio/za-otroke/kdaj-je-pomlad.mp3",
        mp3Sub: "Pesem je uglasbena, uglasbil in izvaja jo kantavtor Peter Andrej."
    },
    {
        title: "Kresnica",
        text: [
            "Jaz sem Cica,",
            "mala kresnica.",
            "Tipalke sem si uredila,",
            "da bom lepa, mila.",
            "",
            "Danes se odpravim v mrak,",
            "saj po dežju čist je zrak.",
            "Mali Leni bom svetila",
            "kot prijazna lučka Vila.",
            "",
            "Tam bo tudi svetli Mik,",
            "moj prijatelj je, kresnik.",
            "Plesala bova kot nekoč,",
            "na dotik v zvezdno noč.",
            "",
            "Malo v gozdu se ustavim,",
            "hrošče, mravlje tam pozdravim,",
            "jim zapojem serenado,",
            "že hitim na promenado.",
            "",
            "Tu se zberemo kresnice,",
            "mestne frajle, lepotice.",
            "O skrivnostih govorimo,",
            "v siju plesa zažarimo.",
            "",
            "Ko na nebu sonce zeha,",
            "se nočna čarovnija neha.",
            "Žarek v rosi se umiva,",
            "trava me v svoj sen pokriva."
        ],
        source: "Ostanek umrle zvezde",
        mp3Url: "/audio/za-otroke/kresnica.mp3",
        mp3Sub: "Pesem je uglasbena, uglasbil in izvaja jo kantavtor Peter Andrej.<br/>Poje Barbara Gabrielle."
    },
    {
        title: "NA PLAŽI",
        text: [
            "TU NA PLAŽI VSAK SE VAŽI:",
            "OČE S POTAPLJAŠKO OPREMO,",
            "MAMA S SVOJO NAJNAJ KREMO,",
            "SESTRA S TRETJIM SLADOLEDOM,",
            "ROK POZIRA Z DALJNOGLEDOM.",
            "",
            "KAKŠEN DOLGČAS!",
            "",
            "ČUDNO, NIHČE NE OPAZI,",
            "KAKO SE IZ MORJA,",
            "PREKO OBZORJA,",
            "TIHA VOJSKA SKRITO PLAZI:",
            "",
            "HIŠKE S POLŽI, ZA NJIMI RAKI,",
            "STRUMNO KORAKAJO VOJAKI,",
            "TJA, KJER JE HLADILNA TORBA,",
            "V NJEJ ZA SENDVIČE BO BORBA.",
            "",
            "JAZ PA V SENCI GENERAL,",
            "ČAKAM NA TRENUTEK PRAVI,",
            "DA ZAPLJUSNE MRZLI VAL",
            "IN VSE VAŽIČE OPLAZI.",
            "",
            "TO BO ZANJE PRAVI ŠOK,",
            "PLAŽO BO PREPLAVIL JOK,",
            "KO LAČNI BODO V TORBO SEGLI,",
            "DA BI SENDVIČE POJEDLI."
        ],
        source: "Galeb"
    },
    {
        title: "KRT",
        text: [
            "ZA HIŠO NA VRTU",
            "SE VSI POSVEČAMO KRTU:",
            "",
            "OČE Z ROKAMI V BOKU,",
            "MAMA OBUPANO V JOKU,",
            "BABI S TANKIM PISKOM,",
            "SESTRA Z ZAČUDENIM VRISKOM.",
            "",
            "JAZ PA V GRADOVE NJEGOVE",
            "SELIM POLŽJE BOGOVE,",
            "NAJ ŠE ONI SLUŽIJO KRTU,",
            "ČE ŽE VLADA NAŠEMU VRTU."
        ],
        source: "Galeb"
    },
    {
        title: "ZIMA",
        text: [
            "ZIMA JE SVET",
            "OVILA V BEL PLET.",
            "",
            "NA NEBO JE PRIPELA",
            "NATRGANO VATO,",
            "GORAM NADELA",
            "KUČMO BOGATO.",
            "",
            "PLETLA JE PLETLA",
            "ODEJE ZA VEJE,",
            "V DLANEH GNETLA",
            "ŠE NEŽNEJŠE PREJE,",
            "",
            "DA JE POSTLALA",
            "ULICE, CESTE",
            "IN JIH ZAČARALA",
            "V BELE NEVESTE."
        ],
        source: "Galeb"
    }
];
